import { InsightItem } from '../types';

export const INSIGHTS_MOCK: InsightItem[] = [
  {
    id: '1',
    title: 'Key Highlights of the New Income Tax Bill, 2025',
    category: 'Income Tax',
    date: '2025-08-18',
    dateModified: '2026-04-30',
    author: 'CA Sagar H R',
    authorId: 'sagar-hr',
    readTime: '3 min read',
    slug: 'new-income-tax-bill-2025',
    summary: 'The new bill aims to simplify direct tax law, making it easier to read, understand, and implement for taxpayers and professionals alike.',
    image: '/og/new-income-tax-bill-2025.svg',
    tags: ['income-tax', 'tax-reform', 'compliance'],
    wordCount: 420
  },
  {
    id: '2',
    title: 'GST 2.0: Major Reforms on the Horizon',
    category: 'GST & Compliance',
    date: '2025-08-17',
    dateModified: '2026-04-30',
    author: 'CA Sagar H R',
    authorId: 'sagar-hr',
    readTime: '2 min read',
    slug: 'gst-reforms-2.0',
    summary: '"GST 2.0" aims to simplify the tax structure by reducing tax slabs and streamlining compliance, potentially boosting economic growth.',
    image: '/og/gst-reforms-2.0.svg',
    tags: ['gst', 'reform', 'msme'],
    wordCount: 343
  },
  {
    id: '3',
    title: 'TDS and TCS Changes from April 2025',
    category: 'Income Tax',
    date: '2025-08-16',
    dateModified: '2026-04-30',
    author: 'CA Sagar H R',
    authorId: 'sagar-hr',
    readTime: '2 min read',
    slug: 'tds-tcs-changes-2025',
    summary: 'Significant changes in TDS and TCS provisions will come into effect, aiming to reduce compliance burdens while ensuring better tax collection.',
    image: '/og/tds-tcs-changes-2025.svg',
    tags: ['tds', 'tcs', 'income-tax', 'compliance'],
    wordCount: 295
  },
  {
    id: '4',
    title: 'Clarity on Income from House Property',
    category: 'Real Estate Taxation',
    date: '2025-08-15',
    dateModified: '2026-04-30',
    author: 'CA Sagar H R',
    authorId: 'sagar-hr',
    readTime: '2 min read',
    slug: 'house-property-income',
    summary: 'The revised Bill has clarified key provisions related to calculating income from house property, providing much-needed clarity for taxpayers.',
    image: '/og/house-property-income.svg',
    tags: ['income-tax', 'real-estate', 'house-property'],
    wordCount: 252
  },
  {
    id: '5',
    title: 'Upcoming GST Compliance Changes in 2025',
    category: 'GST & Compliance',
    date: '2025-08-14',
    dateModified: '2026-04-30',
    author: 'CA Sagar H R',
    authorId: 'sagar-hr',
    readTime: '2 min read',
    slug: 'gst-compliance-updates',
    summary: 'Businesses need to be aware of several changes, including mandatory multi-factor authentication (MFA) and enhanced e-invoicing requirements.',
    image: '/og/gst-compliance-updates.svg',
    tags: ['gst', 'compliance', 'e-invoicing'],
    wordCount: 298
  },
  {
    id: '6',
    title: 'S&P Upgrades India\'s Sovereign Credit Rating',
    category: 'Economic Analysis',
    date: '2025-08-13',
    dateModified: '2026-04-30',
    author: 'CA Sagar H R',
    authorId: 'sagar-hr',
    readTime: '2 min read',
    slug: 'sp-rating-upgrade',
    summary: 'S&P Global Ratings has raised India\'s long-term sovereign credit rating to "BBB" from "BBB-", citing strong economic fundamentals and growth prospects.',
    image: '/og/sp-rating-upgrade.svg',
    tags: ['economy', 'credit-rating', 'investment'],
    wordCount: 266
  }
];
