// TDS and TCS for tax year 2026-27 under the Income-tax Act, 2025, as amended
// by the Finance Act, 2026. Read against the official text of s.392, 393 and
// 394 on incometaxindia.gov.in (6 October 2026); "rates in force" from the
// Finance Act 2026, First Schedule, Part II. `old` is the 1961 Act section the
// row replaces, shown to help readers who know the old numbers.

export interface RateRow {
  /** Stable key, also used in the page's search. */
  id: string;
  payment: string;
  /** Who deducts or collects, when it matters. */
  payer?: string;
  threshold: string;
  rate: string;
  /** The 2025 Act reference. */
  ref: string;
  old: string;
  note?: string;
}

export interface RateGroup {
  id: string;
  name: string;
  description: string;
  rows: RateRow[];
}

export const TDS_TCS_GROUPS: RateGroup[] = [
  {
    id: 'salary',
    name: 'Salary and provident fund',
    description: 'Section 392.',
    rows: [
      {
        id: 'salary',
        payment: 'Salary',
        payer: 'Employer',
        threshold: 'Where the year’s estimated income is above the amount not chargeable to tax',
        rate: 'Average rate on the estimated income for the year',
        ref: 's.392',
        old: '192',
      },
      {
        id: 'pf-withdrawal',
        payment: 'Taxable withdrawal of provident fund balance',
        payer: 'EPF trustees',
        threshold: '₹50,000 or more',
        rate: '10%',
        ref: 's.392(7)',
        old: '192A',
      },
    ],
  },
  {
    id: 'residents',
    name: 'Payments to residents',
    description: 'Section 393(1). Tax is deducted on the whole amount once the threshold is crossed.',
    rows: [
      {
        id: 'insurance-commission',
        payment: 'Insurance commission',
        threshold: '₹20,000 in the year',
        rate: '2% (10% if the payee is a company)',
        ref: 's.393(1) Sl. 1(i)',
        old: '194D',
      },
      {
        id: 'commission',
        payment: 'Commission or brokerage',
        threshold: '₹20,000 in the year',
        rate: '2%',
        ref: 's.393(1) Sl. 1(ii)',
        old: '194H',
      },
      {
        id: 'rent-individual',
        payment: 'Rent paid by an individual or HUF not covered by tax audit',
        threshold: '₹50,000 for a month or part of a month',
        rate: '2%',
        ref: 's.393(1) Sl. 2(i)',
        old: '194-IB',
        note: 'Deducted once, from the rent for the last month of the year or of the tenancy, and paid with Form 141.',
      },
      {
        id: 'rent-machinery',
        payment: 'Rent for plant, machinery or equipment',
        threshold: '₹50,000 for a month or part of a month',
        rate: '2%',
        ref: 's.393(1) Sl. 2(ii)(a)',
        old: '194-I(a)',
      },
      {
        id: 'rent-property',
        payment: 'Rent for land, a building, furniture or fittings',
        threshold: '₹50,000 for a month or part of a month',
        rate: '10%',
        ref: 's.393(1) Sl. 2(ii)(b)',
        old: '194-I(b)',
      },
      {
        id: 'property-purchase',
        payment: 'Purchase of immovable property other than agricultural land',
        payer: 'The buyer',
        threshold: 'Price or stamp duty value of ₹50 lakh or more',
        rate: '1% of the price or the stamp duty value, whichever is higher',
        ref: 's.393(1) Sl. 3(i)',
        old: '194-IA',
        note: 'Paid with Form 141.',
      },
      {
        id: 'joint-development',
        payment: 'Money paid under a joint development agreement',
        threshold: 'None',
        rate: '10%',
        ref: 's.393(1) Sl. 3(ii)',
        old: '194-IC',
      },
      {
        id: 'compulsory-acquisition',
        payment: 'Compensation on compulsory acquisition of immovable property',
        threshold: '₹5,00,000',
        rate: '10%',
        ref: 's.393(1) Sl. 3(iii)',
        old: '194LA',
      },
      {
        id: 'mutual-fund',
        payment: 'Income from mutual fund units',
        threshold: '₹10,000 in the year',
        rate: '10%',
        ref: 's.393(1) Sl. 4(i)',
        old: '194K',
        note: 'Not on capital gains.',
      },
      {
        id: 'business-trust',
        payment: 'Income from a business trust, investment fund or securitisation trust',
        threshold: 'None',
        rate: '10%',
        ref: 's.393(1) Sl. 4(ii) to (iv)',
        old: '194LBA, 194LBB, 194LBC',
      },
      {
        id: 'interest-securities',
        payment: 'Interest on securities',
        threshold: '₹10,000 in the year',
        rate: '10%',
        ref: 's.393(1) Sl. 5(i)',
        old: '193',
      },
      {
        id: 'interest-bank',
        payment: 'Interest from a bank, co-operative bank or post office deposit',
        threshold: '₹50,000 in the year; ₹1,00,000 for a senior citizen',
        rate: '10%',
        ref: 's.393(1) Sl. 5(ii)',
        old: '194A',
      },
      {
        id: 'interest-other',
        payment: 'Other interest, such as on loans',
        threshold: '₹10,000 in the year',
        rate: '10%',
        ref: 's.393(1) Sl. 5(iii)',
        old: '194A',
      },
      {
        id: 'contractors',
        payment: 'Payments to contractors, including supply of labour',
        threshold: '₹30,000 for one payment, or ₹1,00,000 in the year',
        rate: '1% to an individual or HUF; 2% to others',
        ref: 's.393(1) Sl. 6(i)',
        old: '194C',
      },
      {
        id: 'individual-payers',
        payment: 'Contract work, professional fees or commission paid by an individual or HUF not otherwise liable',
        threshold: '₹50 lakh in the year',
        rate: '2%',
        ref: 's.393(1) Sl. 6(ii)',
        old: '194M',
        note: 'Paid with Form 141.',
      },
      {
        id: 'professional-fees',
        payment: 'Fees for professional services, royalty, or a non-compete payment',
        threshold: '₹50,000 in the year',
        rate: '10%',
        ref: 's.393(1) Sl. 6(iii)',
        old: '194J',
      },
      {
        id: 'technical-fees',
        payment: 'Fees for technical services, film royalty, or payments to a call centre',
        threshold: '₹50,000 in the year',
        rate: '2%',
        ref: 's.393(1) Sl. 6(iii)',
        old: '194J',
      },
      {
        id: 'director-fees',
        payment: 'Director’s fees or commission not paid as salary',
        threshold: 'None',
        rate: '10%',
        ref: 's.393(1) Sl. 6(iii)(c)',
        old: '194J',
      },
      {
        id: 'dividend',
        payment: 'Dividend from a domestic company',
        threshold: 'None, but no TDS for an individual paid other than in cash up to ₹10,000 in the year',
        rate: '10%',
        ref: 's.393(1) Sl. 7',
        old: '194',
      },
      {
        id: 'life-insurance',
        payment: 'Taxable payout under a life insurance policy',
        threshold: '₹1,00,000',
        rate: '2% of the income in the payout',
        ref: 's.393(1) Sl. 8(i)',
        old: '194DA',
      },
      {
        id: 'purchase-goods',
        payment: 'Purchase of goods',
        payer: 'A buyer, as defined',
        threshold: 'Purchases from one seller above ₹50 lakh in the year',
        rate: '0.1% of the amount above ₹50 lakh',
        ref: 's.393(1) Sl. 8(ii)',
        old: '194Q',
      },
      {
        id: 'senior-citizen',
        payment: 'Pension and interest of a specified senior citizen, through the bank',
        threshold: 'As applicable',
        rate: 'Rates in force, after deductions and rebate',
        ref: 's.393(1) Sl. 8(iii)',
        old: '194P',
      },
      {
        id: 'perquisites',
        payment: 'Benefits or perquisites from a business or profession',
        threshold: '₹20,000 in the year',
        rate: '10%',
        ref: 's.393(1) Sl. 8(iv)',
        old: '194R',
      },
      {
        id: 'e-commerce',
        payment: 'Payments by an e-commerce operator to sellers on its platform',
        threshold: 'None, but no TDS for an individual or HUF seller with sales up to ₹5 lakh who gives PAN or Aadhaar',
        rate: '0.1% of gross sales',
        ref: 's.393(1) Sl. 8(v)',
        old: '194-O',
      },
      {
        id: 'vda',
        payment: 'Transfer of a virtual digital asset',
        threshold: 'None, but no TDS up to ₹50,000 in the year (₹10,000 for some payers)',
        rate: '1%',
        ref: 's.393(1) Sl. 8(vi)',
        old: '194S',
        note: 'Paid with Form 141 where the payer is an individual or HUF.',
      },
    ],
  },
  {
    id: 'any-person',
    name: 'Payments to anyone',
    description: 'Section 393(3).',
    rows: [
      {
        id: 'winnings',
        payment: 'Winnings from a lottery, crossword, card game or other game',
        threshold: '₹10,000 for one transaction',
        rate: '30%',
        ref: 's.393(3) Sl. 1',
        old: '194B',
      },
      {
        id: 'online-games',
        payment: 'Net winnings from online games',
        threshold: 'None; deducted on withdrawal and at the end of the year',
        rate: '30%',
        ref: 's.393(3) Sl. 2',
        old: '194BA',
      },
      {
        id: 'horse-races',
        payment: 'Winnings from horse races',
        threshold: '₹10,000 for one transaction',
        rate: '30%',
        ref: 's.393(3) Sl. 3',
        old: '194BB',
      },
      {
        id: 'lottery-commission',
        payment: 'Commission on selling lottery tickets',
        threshold: '₹20,000 in the year',
        rate: '2%',
        ref: 's.393(3) Sl. 4',
        old: '194G',
      },
      {
        id: 'cash-withdrawal',
        payment: 'Cash withdrawals from a bank, co-operative bank or post office',
        threshold: 'Above ₹1 crore in the year (₹3 crore for a co-operative society)',
        rate: '2%',
        ref: 's.393(3) Sl. 5',
        old: '194N',
      },
      {
        id: 'nss',
        payment: 'Withdrawal from a National Savings Scheme deposit',
        threshold: '₹2,500',
        rate: '10%',
        ref: 's.393(3) Sl. 6',
        old: '194EE',
      },
      {
        id: 'partners',
        payment: 'Salary, remuneration, commission, bonus or interest to a partner',
        payer: 'The firm',
        threshold: '₹20,000 in the year',
        rate: '10%',
        ref: 's.393(3) Sl. 7',
        old: '194T',
      },
    ],
  },
  {
    id: 'non-residents',
    name: 'Payments to non-residents',
    description:
      'Section 393(2), at the rates in force; a lower treaty rate can apply where the payee gives a tax residency certificate. Surcharge and cess are added.',
    rows: [
      {
        id: 'nr-investment',
        payment: 'Investment income of a non-resident Indian, such as interest on NRO deposits',
        threshold: 'None',
        rate: '20%',
        ref: 's.393(2) Sl. 17',
        old: '195',
      },
      {
        id: 'nr-interest-fc',
        payment: 'Interest on money borrowed in foreign currency',
        threshold: 'None',
        rate: '20%',
        ref: 's.393(2) Sl. 17',
        old: '195',
      },
      {
        id: 'nr-royalty',
        payment: 'Royalty or fees for technical services from the Government or an Indian concern',
        threshold: 'None',
        rate: '20%',
        ref: 's.393(2) Sl. 17',
        old: '195',
      },
      {
        id: 'nr-dividend',
        payment: 'Dividends',
        threshold: 'None',
        rate: '20%',
        ref: 's.393(2) Sl. 17',
        old: '195',
      },
      {
        id: 'nr-stcg',
        payment: 'Short-term capital gains on listed shares and equity funds',
        threshold: 'None',
        rate: '20%',
        ref: 's.393(2) Sl. 17',
        old: '195',
      },
      {
        id: 'nr-ltcg',
        payment: 'Long-term capital gains, including on property',
        threshold: 'On listed shares and equity funds, above ₹1.25 lakh',
        rate: '12.5%',
        ref: 's.393(2) Sl. 17',
        old: '195',
      },
      {
        id: 'nr-other',
        payment: 'Any other sum chargeable to tax',
        threshold: 'None',
        rate: '30% (35% for a foreign company)',
        ref: 's.393(2) Sl. 17',
        old: '195',
      },
      {
        id: 'nr-sports',
        payment: 'Payments to a non-resident sportsperson, entertainer or sports association',
        threshold: 'None',
        rate: '20%',
        ref: 's.393(2) Sl. 1',
        old: '194E',
      },
      {
        id: 'nr-units',
        payment: 'Income from mutual fund units',
        threshold: 'None',
        rate: '20%, or the treaty rate if lower',
        ref: 's.393(2) Sl. 10',
        old: '196A',
      },
    ],
  },
  {
    id: 'tcs',
    name: 'Tax collected at source',
    description: 'Section 394(1). Collected by the seller (or the bank, for remittances) on receipt or debit.',
    rows: [
      {
        id: 'tcs-liquor',
        payment: 'Sale of alcoholic liquor',
        threshold: 'None',
        rate: '2%',
        ref: 's.394(1) Sl. 1',
        old: '206C(1)',
      },
      {
        id: 'tcs-tendu',
        payment: 'Sale of tendu leaves',
        threshold: 'None',
        rate: '2%',
        ref: 's.394(1) Sl. 2',
        old: '206C(1)',
      },
      {
        id: 'tcs-timber',
        payment: 'Sale of timber or forest produce',
        threshold: 'None',
        rate: '2%',
        ref: 's.394(1) Sl. 3',
        old: '206C(1)',
      },
      {
        id: 'tcs-scrap',
        payment: 'Sale of scrap',
        threshold: 'None',
        rate: '2%',
        ref: 's.394(1) Sl. 4',
        old: '206C(1)',
      },
      {
        id: 'tcs-minerals',
        payment: 'Sale of coal, lignite or iron ore',
        threshold: 'None',
        rate: '2%',
        ref: 's.394(1) Sl. 5',
        old: '206C(1)',
      },
      {
        id: 'tcs-vehicle',
        payment: 'Sale of a motor vehicle or notified goods',
        threshold: 'Above ₹10 lakh',
        rate: '1%',
        ref: 's.394(1) Sl. 6',
        old: '206C(1F)',
      },
      {
        id: 'tcs-lrs-education',
        payment: 'Money sent abroad for education or medical treatment',
        payer: 'Authorised dealer (the bank)',
        threshold: 'Above ₹10 lakh in the year',
        rate: '2%; nil where paid from an education loan',
        ref: 's.394(1) Sl. 7(a)',
        old: '206C(1G)',
      },
      {
        id: 'tcs-lrs-other',
        payment: 'Money sent abroad for other purposes',
        payer: 'Authorised dealer (the bank)',
        threshold: 'Above ₹10 lakh in the year',
        rate: '20%',
        ref: 's.394(1) Sl. 7(b)',
        old: '206C(1G)',
      },
      {
        id: 'tcs-tour',
        payment: 'Overseas tour package',
        threshold: 'None',
        rate: '2%',
        ref: 's.394(1) Sl. 8',
        old: '206C(1G)',
      },
      {
        id: 'tcs-parking',
        payment: 'Use of a parking lot, toll plaza, mine or quarry for business',
        payer: 'Licensor or lessor',
        threshold: 'None',
        rate: '2%',
        ref: 's.394(1) Sl. 9',
        old: '206C(1C)',
      },
    ],
  },
];

/** Due dates and forms under Rules 215, 218 and 219 of the Income-tax Rules, 2026. */
export const TDS_DUE_DATES: { what: string; when: string }[] = [
  { what: 'Pay tax deducted or collected', when: 'By the 7th of the next month; for March, by 30 April' },
  {
    what: 'Form 141: rent paid by individuals, property purchase, payments by individuals above ₹50 lakh, digital assets',
    when: 'Within 30 days from the end of the month of deduction',
  },
  {
    what: 'Quarterly statements: Form 138 (salary), 140 (other payments to residents), 144 (non-residents), 143 (TCS)',
    when: '31 July, 31 October, 31 January and 31 May',
  },
  { what: 'Form 130: certificate of tax deducted from salary', when: 'By 15 June after the tax year' },
  {
    what: 'Form 131 (other TDS) and Form 133 (TCS) certificates',
    when: 'Within 15 days of the quarterly statement due date',
  },
  { what: 'Form 132: certificate for Form 141 payments', when: 'Within 15 days of the Form 141 due date' },
];

/** Rules worth knowing, shown below the table. */
export const TDS_NOTES: string[] = [
  'Without the payee’s PAN, tax is deducted at the normal rate or 20% (5% for purchase of goods and e-commerce payments), whichever is higher. TCS is collected at twice the normal rate or 5%, whichever is higher, up to 20% (s.397).',
  'A resident who expects no tax for the year can give a declaration in Form 121 (formerly 15G and 15H) for interest, dividends, rent and some other payments.',
  'For lower or nil deduction, the payee applies to the Assessing Officer in Form 128.',
  'A buyer who will use tendu leaves, timber, scrap, minerals or liquor for manufacturing or generating power, and not for trading, can give the seller a declaration in Form 127 so that no TCS is collected.',
];
